# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94995ae7b38f06e4dd5d8dbc1e33828b82fbc87571328d885598ddf119473377b5859abe16b552977a12bde53c872d177a9e7c50d91dc4e2d97cc4f32a3b7ce8

test:
  secret_key_base: aae35146ff1b513380e347c3141d3917f5f914390d795e5567ae3fab594d8afc66d4c39ced3545eb4e5b3ab1c8cc3b12cae6f08f4ec5fdd7156abe89eeecff89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
